# Generated by Django 5.1.7 on 2025-03-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_alter_post_img_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='number_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cp.post'),
        ),
    ]
