# Generated by Django 5.1.7 on 2025-03-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0003_alter_comment_number_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(db_collation='nocase', max_length=255),
        ),
    ]
